### PR TITLE
Update Sponsors

### PR DESCRIPTION
**Pull request by anellis**
Remove Owen and Industrious and add Adzerk as a sponsor

### CODE REVIEW

**Comment by drapergeek** [comment]
Let's leave Owen in until I get an official answer there.

**Comment by anellis** [comment]
Updated!

**Comment by drapergeek** [comment]
Uh...yea...about that...just confirmed he won't be there 😄 😭

**Comment by anellis** [comment]
... I just can't with you sometimes. Updated again.

**Comment by drapergeek** [comment]
LGTM

**Pull request merged**
