### PR TITLE
Update event

### PR DESCRIPTION
**Pull request by anellis**

### CODE REVIEW

**Comment by drapergeek** [comment]
Mind posting a screenshot of moving the mailchimp around?

**Comment by anellis** [comment]
Top of page: 
image

Scroll down:

image

**Comment by drapergeek** [comment]
Any reason for the move?

I feel like it's a smaller leap to ask someone to sign up for the mailing list so I liked it being the first thing.

**Comment by anellis** [comment]
I want the main focus to be to sign up for the next event. I think signing up for the mailing list is fine but what we actually want most is for people to attend, right?

**Comment by drapergeek** [comment]
>what we actually want most is for people to attend, right?

There's a tradeoff between what we want most and what we can get people to do. My theory was to get them on the mailing list so that if the dates don't work, they're on the hook.

Theory is great, in practice who knows? I'm at a 5 on the scale http://blog.capwatkins.com/the-sliding-scale-of-giving-a-fuck, use your best judgement ™️ 😄

**Comment by anellis** [comment]
I'm only at a 2 on the scale so I'll leave it as is for now

**Comment by anellis** [comment]
Good to merge besides that?

**Comment by drapergeek** [comment]
:shipit:

**Pull request merged**
