### PR TITLE
Add empty Intro to Web slides to use as an example

### PR DESCRIPTION
**Pull request by mxhold**
This can be used as a base for the other talks so we have a nice/consistent slide format.

Hosting the slides on the site also has the added benefit of making it very easy to share to the participants after.

### CODE REVIEW

**Comment by drapergeek** [comment]
How about renaming this to just example and leaving it here for future new presentations to copy from?

**Comment by mxhold** [comment]
Great idea. Done!

**Comment by drapergeek** [comment]
I'm good with this overall, can you split the gem updates into a separate commit? Having those in with this HTML change seems odd.

**Comment by mxhold** [comment]
Ah good catch. Didn't mean to include those but might as well. Now its in a separate commit.

**Comment by drapergeek** [comment]
:shipit: :dancer: :balloon: :other_fun_emoji:

**Pull request merged**
