### PR TITLE
Add slides for MVC Talk

### PR DESCRIPTION
**Pull request by drapergeek**
I'll wait on @mxhold to get his slides working before this is merged.

### CODE REVIEW

**Comment by mxhold** [comment]
Everything should be fixed for mine! :shipit:

**Comment by drapergeek** [comment]
@mxhold Is your css scoped? Your slides look great on production, mine however do not.

**Comment by mxhold** [comment]
I had issues with the paths to the assets so if you made your slides from my original ones they were wrong. First I had all mine like "assets/web1.png", which would work locally but once it was on production it was coming through as "intro_to_web/assets/web1.png" so I went back and changed them to "../assets/web1.png" which fixed it.

**Comment by drapergeek** [comment]
Thank you sir!

**Pull request merged**
